services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tspay-subhub-app
    restart: always
    ports:
      - "2139:2139" # Mapping host port to container port
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs # Mounting host 'logs' folder to container '/app/logs'
    # Optional: ensure logs directory exists on host or it will be created as root by Docker
    # In Windows, this is usually fine.
