basePath: /api
definitions:
  utils.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: API Server for Tspay Subhub.
  title: Tspay Subhub API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Get the status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Health Check
      tags:
      - health
  /incoming:
    get:
      consumes:
      - application/json
      description: Handles incoming requests for Tspay Subhub
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Incoming Handler
      tags:
      - incoming
swagger: "2.0"
